feat(lap-169): multiple choice for reading lessons
Lapin-Learn/mobile pull request #18
Opened 2024-09-19 09:04 UTC by MinEn1712

**DONE**
- Multiple Choice layout (single choice)
- Modal for correct and incorrect answers
- Get game data to display in After Lesson
- i18n for Multiple Choice

**NOT DONE**
- API intergrate (chua co data duoi db :c)

2024-09-19 13:50 UTC, vmathu requested changes

2024-09-19 13:50 UTC, vmathu commented on assets/images/cross-circle.svg
![image](https://github.com/user-attachments/assets/19bfa344-9b69-49b8-afc7-42f85fed8f7d)
do máy t hay svg nó lỗi dị

2024-09-19 13:50 UTC, vmathu commented on components/molecules/ReadingContainer.tsx
> +    <ScrollView className='max-h-80 rounded-[8px] border-[1px] border-neutral-900 p-4'>
```suggestion
    <ScrollView className='max-h-80 rounded-lg border border-neutral-900 p-4'>
```

2024-09-19 13:50 UTC, vmathu commented on components/molecules/exercise/MultipleChoice.tsx
> +];
đc thì tách file mock data nha

2024-09-19 13:50 UTC, vmathu commented on components/molecules/exercise/types.ts
> +  questionType: string;
này có enum hem

2024-09-19 13:51 UTC, MinEn1712 commented on assets/images/cross-circle.svg
ủa vài :")))) để t coi lại nhen huheo

2024-09-19 14:39 UTC, Huy203 reviewed
coi đc thì tạo 1 component answerModal nhe, thấy cx giống nhau

2024-09-19 14:39 UTC, Huy203 commented on services/utils.ts
> +export const convertSecondsToMinutes = (seconds: number): string => {
chuyển qua lib/util nhe

2024-09-19 15:21 UTC, NganTrucLe commented on components/molecules/ReadingContainer.tsx
> +    <ScrollView className='max-h-80 rounded-[8px] border-[1px] border-neutral-900 p-4'>
này để t coi cái plugin r kiu bây cài cho, nó có suggest mí này á, k sửa thì nó sẽ warning 💀

2024-09-19 15:43 UTC, MinEn1712 commented on components/molecules/ReadingContainer.tsx
> +    <ScrollView className='max-h-80 rounded-[8px] border-[1px] border-neutral-900 p-4'>
![Screenshot 2024-09-19 224153](https://github.com/user-attachments/assets/07545a60-b83f-4380-855d-035ba99db098)

2024-09-19 15:43 UTC, MinEn1712 commented on components/molecules/ReadingContainer.tsx
> +    <ScrollView className='max-h-80 rounded-[8px] border-[1px] border-neutral-900 p-4'>
tại cái lg nó dị nek hic :") md là 12, sm là 4 :"))))

2024-09-19 15:46 UTC, MinEn1712 commented on components/molecules/exercise/types.ts
> +  questionType: string;
này cái commit mới nhất t mới đổi thành type é m coi thử nhen

2024-09-19 16:06 UTC, vmathu approved these changes

2024-09-21 17:29 UTC, vmathu requested changes

2024-09-21 17:29 UTC, vmathu commented on app/lesson/[lessonId].tsx
> +  const { data: questions, isLoading: questionsLoading } = useLessonQuestions({ lessonId });
s cái fetch trả lỗi á m 
![image](https://github.com/user-attachments/assets/203b8a29-f617-4a90-b9be-1ae292aaad1b)

2024-09-21 17:29 UTC, vmathu commented on components/molecules/lesson/AfterLesson.tsx
![image](https://github.com/user-attachments/assets/6a7b1bac-c459-494e-979f-ebddaf836c1e)
cái after lesson t test trên ios device bị lỗi nì

2024-09-22 05:56 UTC, Huy203 commented on components/molecules/lesson/AfterLesson.tsx
này phải build mới được nha

2024-09-22 08:23 UTC, MinEn1712 commented on app/lesson/[lessonId].tsx
> +  const { data: questions, isLoading: questionsLoading } = useLessonQuestions({ lessonId });
à này do chưa có cái lesson cho pre_ielts trên db é :c mở screen questionType nó hem có cái lessonList nên là nó hem có truyền cái lessonId nào qua bên screen làm bài é

2024-09-22 08:23 UTC, MinEn1712 commented on app/lesson/[lessonId].tsx
> +  const { data: questions, isLoading: questionsLoading } = useLessonQuestions({ lessonId });
t mới tạo data rùi nhen

2024-09-22 11:13 UTC, vmathu commented on lib/interfaces.ts
> +  cerfLevel: string;
này chắc có enum ó

2024-09-23 16:54 UTC, Huy203 approved these changes

2024-09-24 01:28 UTC, vmathu24 requested changes

2024-09-24 01:28 UTC, vmathu24 commented on app/exercise/[exerciseId]/[questionTypeId]/index.tsx
> +  const [curLessonId, setCurLessonId] = useState<number | null>(currentLesson?.id || 0);
```suggestion
  const [curLessonId, setCurLessonId] = useState<number>(currentLesson?.id || lessons?.lessons[0].id || 0);
```

2024-09-24 09:24 UTC, merged