feat(lap-186): update audio component
Lapin-Learn/mobile pull request #20
Opened 2024-09-22 06:57 UTC by Huy203

2024-09-22 12:09 UTC, vmathu requested changes

2024-09-22 12:09 UTC, vmathu commented on components/molecules/SeekBar.tsx
> +  const INITIAL_THUMB_SIZE = 14;
constant mang ra ngoài component lun i

2024-09-22 12:09 UTC, vmathu commented on app/(tabs)/mission/index.tsx
> +      <TrackAudio />
s để audio trong mission á

2024-09-22 12:09 UTC, vmathu commented on app/_layout.tsx
![image](https://github.com/user-attachments/assets/83c020d8-82d1-48f7-a2e0-844b1c764bd7)

2024-09-22 12:09 UTC, vmathu commented on components/molecules/TrackAudio.tsx
> +  };
s comment á

2024-09-22 12:09 UTC, vmathu commented on app/(tabs)/mission/index.tsx
![image](https://github.com/user-attachments/assets/4c407331-1898-45c9-ad42-4bf7c5479959)
k play đc nha, nhấn là sẽ warning

2024-09-22 18:15 UTC, vmathu requested changes

2024-09-22 18:15 UTC, vmathu commented on components/molecules/TrackAudio.tsx
> +  );
![image](https://github.com/user-attachments/assets/8fcfff40-4624-424c-b884-a9a9973f9912)
canh giữa lại nè

2024-09-22 18:15 UTC, vmathu commented on lib/trackPlayer.ts
đổi tab hay thoát app đều k dừng á

2024-09-22 18:15 UTC, vmathu commented on components/molecules/TrackAudio.tsx
> +        <Action />
nhấn 3 lần mới stop nhạc :'))

2024-09-22 18:24 UTC, vmathu commented
vẫn còn 2 cái này, warn lúc vào lần đầu và error lúc reload nha, nhma vẫn play nhạc đc :")) chứ cái cũ là t chịu lun á :'))
![image](https://github.com/user-attachments/assets/efe28532-3f0c-4f2b-93dd-cc02890cf38a)

2024-09-23 04:45 UTC, Huy203 commented on app/(tabs)/mission/index.tsx
> +      <TrackAudio />
để test thui

2024-09-23 16:49 UTC, vmathu approved these changes

2024-09-23 16:58 UTC, MinEn1712 approved these changes

2024-09-24 13:48 UTC, merged