feat(lap-225): profile layout
Lapin-Learn/mobile pull request #24
Opened 2024-09-26 10:57 UTC by Huy203

Dùng PlatformView thay cho SafeAreaView sau này
Chạy command `generate-locales` để update folder locales khi thêm file mới
Prebuild và Install lại app để check SplashScreen

2024-09-26 14:13 UTC, vmathu commented
![image](https://github.com/user-attachments/assets/28bcffda-0094-49c4-bb6b-9434d02b2101)
api hiện tại cái có `/` đầu cái k á, k một là có hết thì `.env` api k có `/` cuối, hai là ngược lại, m chọn một cái r báo frontend thống nhất nha

2024-09-26 14:16 UTC, vmathu commented
onboarding thì t đang k chắc first time nó có hiện k, kiểu t start thì vào sẵn, log out ra k có đẩy về onboarding, nhma vd t có sửa code để nó load lại thì có đẩy về nha :'))

2024-09-26 14:17 UTC, vmathu requested changes

2024-09-26 14:17 UTC, vmathu commented on app/on-boarding.tsx
> +          <Text className='text-body font-semibold text-white'>Get Started</Text>
ch có i18n hẻ

2024-09-26 14:17 UTC, vmathu commented on app/on-boarding.tsx
> +        <Button className='flex-row items-center justify-center gap-x-1 px-4 py-3.5'>
nhấn get started thì qua sign up he

2024-09-28 07:06 UTC, vmathu approved these changes

2024-09-28 13:35 UTC, MinEn1712 approved these changes

2024-09-28 14:07 UTC, merged