refactor(lap-232): refactor daily lesson game
Lapin-Learn/mobile pull request #25
Opened 2024-09-26 11:19 UTC by MinEn1712

- State management: useGameStore
- Handle different types of Multiple Choice game
- Change answer to array

2024-09-26 14:41 UTC, vmathu requested changes

2024-09-26 14:41 UTC, vmathu commented on components/molecules/ChoiceButton.tsx
![Screenshot_1727361115](https://github.com/user-attachments/assets/ed1681ee-4159-49f8-912d-3a8208e053d3)
check lại style nhe

2024-09-28 07:12 UTC, vmathu approved these changes

2024-09-28 09:50 UTC, Huy203 approved these changes

2024-09-28 15:32 UTC, merged