LAP-251: [FE] Congratulations screen when get new level and rank
Lapin-Learn/mobile pull request #38
Opened 2024-10-03 18:55 UTC by vmathu

2024-10-04 03:42 UTC, Quan0308 requested changes
- Bỏ chữ KN sau xp mới khi hiện level up
- Chỉnh hiệu ứng xoay khi rank up như level up

2024-10-04 06:24 UTC, NganTrucLe requested changes
![image](https://github.com/user-attachments/assets/f30d0658-57a4-4164-97ea-5735ca7e854d)
Gắn ảnh ava mấy question type ở đây, với lại xem có lấy được tổng điểm kinh nghiệm của cái questionType đó chưa để cập nhật lun nè

2024-10-04 11:11 UTC, MinEn1712 commented on components/molecules/exercise/QuestionTemplate.tsx
> +            timer: getDuration(duration),
hú nì chắc m dùng cái duration sau khi gọi mutation trả về nha, để thêm cái getDuration nữa nó bị sai tgian á, duration t làm thực tế là 7s mà hiện UI là 8s nek :[
![Screenshot 2024-10-04 175524](https://github.com/user-attachments/assets/fc490fde-b20a-480d-8dd5-c52120dfb9f4)
![Screenshot_20241004-175534](https://github.com/user-attachments/assets/f194b9a3-b637-44c8-a798-84234cca5c23)
ets/08163447-2249-4cbb-a6ad-07d40e464cc0)

2024-10-04 11:11 UTC, MinEn1712 commented on hooks/react-query/useDailyLesson.ts
> +      setMilestones(response.milestones);
ye như cmt trên thì t suggest thêm setCompleteTime hay đại loại dị ở đây he

2024-10-05 06:09 UTC, Huy203 approved these changes

2024-10-05 06:10 UTC, MinEn1712 approved these changes

2024-10-05 06:12 UTC, NganTrucLe approved these changes

2024-10-05 06:12 UTC, merged