fix(lap-379): update verify flow when user enter invalid otp
Lapin-Learn/mobile pull request #71
Opened 2024-10-26 03:40 UTC by Huy203

2024-10-26 04:42 UTC, vmathu commented on locales/vi/auth.json
> +    "resendCodeWithTime": "Gửi lại mã {{time}} giây",
```suggestion
    "resendCodeWithTime": "Gửi lại mã sau {{time}} giây",
```

2024-10-26 16:03 UTC, NganTrucLe requested changes

2024-10-26 16:03 UTC, NganTrucLe commented on app/auth/(forgot-password)/verify.tsx
> +                        if (text.length === 0) {
define a function outside, no complex inline logic

2024-10-26 16:03 UTC, NganTrucLe commented on components/molecules/NavigationBar.tsx
> +          )}>
change to StyleSheet

2024-10-26 16:03 UTC, NganTrucLe commented on components/molecules/NavigationBar.tsx
>            {headerTitle && <Text className='font-ibold text-title-4 text-black'>{headerTitle}</Text>}
change to StyleSheet

2024-10-29 09:38 UTC, NganTrucLe approved these changes

2024-10-29 09:39 UTC, merged