style(lap-364): hide unimplement item in navbar, fb authen, skill pro…
Lapin-Learn/mobile pull request #73
Opened 2024-10-26 16:34 UTC by vmathu

…gress, random exercises, jump to next band and share social btn and remove console log

2024-10-28 07:51 UTC, NganTrucLe requested changes
MVP sẽ không làm speaking nên chắc cho nhấn speaking ra 1 trang not supported yet nhe :"> sr Thư 
![image](https://github.com/user-attachments/assets/d7584bbe-9f30-4fc9-a6ae-a298784b600a)
Ẩn cả trong profile 
![image](https://github.com/user-attachments/assets/5adf7926-fb81-4013-aa48-a5a9c9d1d9ee)
chỗ GG chắc để thành nút dài vs text "Sign in with <Gg logo> Google" hen, còn "or sign in with" -> "or"
![image](https://github.com/user-attachments/assets/f57914ed-27b5-486f-9843-73e4aac647b9)

2024-10-28 08:35 UTC, NganTrucLe commented
à vs có cái bug này nhỏ xíu à, chắc sẽ remove cái question term này luôn chứ để vừa trùng vừa chiếm diện tích, có j m sửa giúp t luôn nha 
![image](https://github.com/user-attachments/assets/c85dce39-622d-4e6c-9c8f-696dc2fb9485)
https://datn.atlassian.net/browse/LAP-373

2024-10-29 13:34 UTC, NganTrucLe approved these changes

2024-10-29 14:33 UTC, NganTrucLe approved these changes

2024-10-29 14:36 UTC, merged

2024-10-29 14:37 UTC, vmathu commented
![Screenshot_1730211640](https://github.com/user-attachments/assets/1fd4b59b-7939-42a2-b983-eeec60316d14)
![Screenshot_1730211665](https://github.com/user-attachments/assets/6430c07e-d450-43ed-aa5b-668b435e33d6)
![Screenshot_1730211687](https://github.com/user-attachments/assets/3b0dd562-3398-4a57-9b39-42610ee5c7df)
![Screenshot_1730211690](https://github.com/user-attachments/assets/052d53e4-61d8-4e7d-bb18-4c49fe41cf78)